# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [master]
  push:
    branches: [invoke_trigger]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single  job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci
      - name: lint and test
        run: |
          npm run lint
          npm run test:cov
      - name: Coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  publish:
    if: github.ref == 'refs/heads/invoke_trigger'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: version
        run: |
          git checkout -f -b version-branch
          echo version=`node -p "require('./package.json').version"` >> $GITHUB_ENV
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: trigger artifacts registry
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/kube-HPC/artifacts-registry/dispatches
          event_type: trigger
          client_payload: '{"version": "${{env.version}}" , "wrapper": "nodejs" , "action": "dev-version" }'
        env:
          GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"
